=== aspectran/aspectran/aspectran-web/config/aspectran/dtd/aspectran-1.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT aspectran (settings? | typeAliases* | import* | bean* | translet* | aspect*)*>
<!ATTLIST aspectran
namespace CDATA #IMPLIED
>

<!ELEMENT settings (setting*)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | reference | null)*>
<!ATTLIST item
name CDATA #IMPLIED
value CDATA #IMPLIED
type CDATA #IMPLIED
valueType CDATA #IMPLIED
defaultValue CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA | reference | null)*>
<!ATTLIST value
name CDATA #IMPLIED
tokenize (true | false) #IMPLIED
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
bean CDATA #IMPLIED
parameter CDATA #IMPLIED
attribute CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>

<!ELEMENT properties (item*)>

<!ELEMENT arguments (item*)>

<!ELEMENT parameters (item*)>

<!ELEMENT null EMPTY>

<!ELEMENT aspect (joinpoint?, properties?, action*, before?, after?, finally?, around?)>
<!ATTLIST aspect
id ID #IMPLIED
>

<!ELEMENT joinpoint (pointcut*)>
<!ATTLIST joinpoint
target (request | response | scheduler | bean | translet | action) #REQUIRED
>

<!ELEMENT pointcut (#PCDATA)>
<!ATTLIST pointcut
pattern CDATA #IMPLIED
>

<!ELEMENT once (properties? | action?)*>
<!ELEMENT before (properties? | echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT after (properties? | echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT finally (properties? | echo? | action? | transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT around (properties? | echo? | action? | transform? | dispatch? | redirect? | forward?)*>

<!ELEMENT bean (features?, constructor?, properties*)>
<!ATTLIST bean
id ID #REQUIRED
class CDATA #IMPLIED
scope (singleton | prototype | request | session | application) #IMPLIED
factoryMethod CDATA #IMPLIED
initMethod CDATA #IMPLIED
destoryMethod CDATA #IMPLIED
lazyInit (true | false) #IMPLIED
parent CDATA #IMPLIED
>

<!ELEMENT features (class?, scope?, factoryMethod?, initMethod?, destroyMethod?, lazyInit?)>

<!ELEMENT class (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT factoryMethod (#PCDATA)>
<!ELEMENT initMethod (#PCDATA)>
<!ELEMENT destroyMethod (#PCDATA)>
<!ELEMENT lazyInit (#PCDATA)>

<!ELEMENT constructor (arguments?)>

<!ELEMENT translet (request?, contents?, response?, transform?, dispatch?, redirect?, forward?, exception?)>
<!ATTLIST translet
name CDATA #REQUIRED
hidden (true | false) #IMPLIED
parent CDATA #IMPLIED
>

<!ELEMENT request (attributes?, multiparts?)>
<!ATTLIST request
method CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>

<!ELEMENT multiparts (fileItem*)>

<!ELEMENT fileItem (allowFileExtentions? | denyFileExtentions?)>
<!ATTLIST fileItem
name CDATA #REQUIRED
>

<!ELEMENT allowFileExtentions (#PCDATA)>
<!ELEMENT denyFileExtentions (#PCDATA)>

<!ELEMENT contents (content*)>

<!ELEMENT content (echo? | action? | include?)*>
<!ATTLIST content
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | item | value | null)*>
<!ATTLIST echo
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
id CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT include (attributes?)>
<!ATTLIST include
id CDATA #IMPLIED
translet CDATA #REQUIRED
hidden (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST response
characterEncoding CDATA #IMPLIED
default CDATA #IMPLIED
>
<!ELEMENT exception (responseByContentType?, defaultResponse?)>

<!ELEMENT responseByContentType (transform? | dispatch? | redirect? | forward?)*>
<!ELEMENT defaultResponse (transform? | dispatch? | redirect? | forward?)>

<!ELEMENT transform (echo | action | include | template)*>
<!ATTLIST transform
id CDATA #IMPLIED
type CDATA #REQUIRED
contentType CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
encoding CDATA #IMPLIED
noCache (true | false) #IMPLIED
>

<!ELEMENT dispatch (echo? | action? | include? | template)*>
<!ATTLIST dispatch
id CDATA #IMPLIED
contentType CDATA #IMPLIED
>

<!ELEMENT redirect (echo* | action* | include* | url? | parameters*)>
<!ATTLIST redirect
id CDATA #IMPLIED
contentType CDATA #IMPLIED
url CDATA #IMPLIED
translet CDATA #IMPLIED
excludeNullParameters CDATA #IMPLIED
>
<!ELEMENT url (#PCDATA)>

<!ELEMENT forward (echo* | action* | include* | parameters*)>
<!ATTLIST forward
id CDATA #IMPLIED
contentType CDATA #IMPLIED
translet CDATA #IMPLIED
>

=== aspectran/aspectran/aspectran-web/config/aspectran/aspectran-example-scheduler.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "./dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePattern" value="/scheduler/*.job"/>
	</settings>
	
	<bean id="schedulerFactory" class="org.quartz.impl.StdSchedulerFactory" scope="singleton">
		<constructor>
			<arguments>
				<item type="properties">
					<value name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler</value>
					<value name="org.quartz.scheduler.rmi.export">false</value>
					<value name="org.quartz.scheduler.rmi.proxy">false</value>
					<value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
					<value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
					<value name="org.quartz.threadPool.threadCount">10</value>
					<value name="org.quartz.threadPool.threadPriority">5</value>
					<value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
					<value name="org.quartz.jobStore.misfireThreshold">60000</value>
					<value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
				</item>
			</arguments>
		</constructor>
	</bean>
	
	<bean id="exampleJobAction" class="com.aspectran.example.scheduler.ExampleJobAction" scope="singleton"/>
	
	<aspect id="exception2">
		<joinpoint target="translet" scope="translet">
			<pointcut>/scheduler/*</pointcut>
		</joinpoint>
		<advice>
			<exceptionRaized>
				<responseByContentType exceptionType="java.lang.reflect.InvocationTargetException">
					<transform contentType="text/xml" type="transform/xml">
						<echo>
							<item type="map">
								<value name="errorCode">E0001</value>
								<value name="message">error occured.</value>
							</item>
						</echo>
					</transform>
				</responseByContentType>
			</exceptionRaized>
		</advice>
	</aspect>
	
<!-- 	
	<aspect id="scheduler0">
		<joinpoint target="scheduler">
			<pointcut type="simpleTrigger">
				startDelay: 500
				repleatInterval: 3000
				repeatCount: 10
			</pointcut>
		</joinpoint>
		<advice bean="schedulerFactory">
			<job translet="/scheduler1/test1.job"/>
			<job translet="/scheduler1/test2.job"/>
		</advice>
	</aspect>
-->
	<aspect id="scheduler1">
		<joinpoint target="scheduler">
			<pointcut type="cronTrigger">0/5 * * * * ?</pointcut>
		</joinpoint>
		<advice bean="schedulerFactory">
			<job translet="hello" disabled="false"/>
			<job translet="countTo10" disabled="false"/>
			<job translet="countTo10.xml" disabled="true"/>
		</advice>
	</aspect>
	
	<aspect id="scheduler2">
		<joinpoint target="scheduler">
			<pointcut type="cronTrigger">0/5 * * * * ?</pointcut>
		</joinpoint>
		<advice bean="schedulerFactory">
			<job translet="errorCaused" disabled="true"/>
		</advice>
	</aspect>
	
	<translet name="hello">
		<request>
			<attributes>
				<item name="my_name_is">aspectran</item>
			</attributes>
		</request>
		<transform type="transform/text">
			<template>
				hello~ @{my_name_is}!!
			</template>
		</transform>
	</translet>

	<translet name="countTo10">
		<transform type="transform/text">
			<action id="result1" bean="exampleJobAction" method="countTo10"/>
			<template>
@{result1}
			</template>
		</transform>
	</translet>

	<translet name="countTo10twice">
		<action id="result1" bean="exampleJobAction" method="countTo10"/>
		<action id="result2" bean="exampleJobAction" method="countTo10"/>
		<transform type="transform/text">
			<template>
(first)
@{result1}
(second)
@{result2}
			</template>
		</transform>
	</translet>

	<translet name="countTo10.xml">
		<transform type="transform/xml">
			<action id="result" bean="exampleJobAction" method="countTo10AsArray"/>
		</transform>
	</translet>

	<translet name="countTo10ext">
		<response>
			<transform type="transform/text">
				<action id="result" bean="exampleJobAction" method="countTo10"/>
				<template>
					@{result}
				</template>
			</transform>
		</response>
		<response name=".xml">
			<transform type="transform/xml">
				<action bean="exampleJobAction" method="countTo10AsArray"/>
			</transform>
		</response>
	</translet>

	<translet name="errorCaused">
		<transform type="transform/xml">
			<action id="result" bean="exampleJobAction" method="errorCaused"/>
		</transform>
	</translet>

</aspectran>

=== aspectran/aspectran/trunk/aspectran-web/config/aspectran/aspectran.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "./dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePattern" value="/test/../*.do"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
		<setting name="multiActivityEnable" value="true"/>
	</settings>
	
	<aspect id="requestRule">
		<joinpoint target="request"/>
		<properties>
			<item name="characterEncoding">utf-8</item>
			<item name="maxRequestSize">10M</item>
			<item name="temporaryFilePath">/d:/</item>
		</properties>
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
			<dispatch id="jsp" contentType="text/html">
				<template>/WEB-INF/jsp/hello.jsp</template>
			</dispatch>
		</after>
	</aspect>

	<aspect id="responseRule">
		<joinpoint target="response"/>
		<properties>
			<item name="characterEncoding">utf-8</item>
			<item name="defaultContentType">text/html</item>
			<item name="viewDispatcher">org.jhlabs.translets.web.JspViewDispatcher</item>
		</properties>
	</aspect>

	<aspect id="bean1">
		<joinpoint target="bean">
			<pointcut>front/*</pointcut>
		</joinpoint>
		<properties>
			<item name="characterEncoding">utf-8</item>
			<item name="defaultContentType">text/html</item>
			<item name="viewDispatcher">org.jhlabs.translets.web.JspViewDispatcher</item>
		</properties>
	</aspect>

	<!--
		before: access logging
		after: error logging 
	-->
	<aspect id="logging">
		<joinpoint target="action">
			<pointcut>front.action1</pointcut>
		</joinpoint>
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
			<dispatch id="jsp" contentType="text/html">
				<template>/WEB-INF/jsp/hello.jsp</template>
			</dispatch>
		</after>
	</aspect>

	<!--
		scheduler
	-->
	<aspect id="scheduler1">
		<joinpoint target="scheduler">
			<pointcut>* * 10 0</pointcut>
		</joinpoint>
		<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
			<properties>
				<item name="variable1">error</item>
				<item name="variable2">0001</item>
			</properties>
		</action>
		<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
			<properties>
				<item name="variable1">error</item>
				<item name="variable2">0001</item>
			</properties>
		</action>
	</aspect>

	<!--
		Matching targets:
			request: reserved
			response: reserved
			bean: each time it is called
			translet: each time it is called
			action: each time it is called
		getAspectObject:
			a return data of <before> action.
	-->
	<aspect id="sqlmap">
		<joinpoint target="translet">
			<pointcut>
				front/a/*
				exclude(front/a/A*)
			</pointcut>
		</joinpoint>
		<before>
			<action bean="common.ticket.t1" method="begin">
				<arguments>
					<item name="stmtId">aaaaaaa</item>
				</arguments>
			</action>
		</before>
		<after>
			<action bean="common.ticket.t1" method="end">
				<arguments>
					<item name="stmtId">aaaaaaa</item>
				</arguments>
			</action>
		</after>
	</aspect>
	
	<bean id="aaa" class="org.jhlabs.translets.test*..*" scope="singleton"/>

	<import resource="ticket-rule.xml"/>
	<import resource="exception-rule.xml"/>
	<import resource="front-translets.xml"/>
	<import resource="ajax-translets.xml"/>
	
</aspectran>

=== aspectran/aspectran/trunk/aspectran.example/config/aspectran/sample/aspectran-sample.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "../dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePatternPrefix" value="/test/"/>
		<setting name="transletNamePatternSuffix" value=".do"/>
		<setting name="transletNamePattern" value="/test/*.do"/>
		<setting name="transletInterfaceClass" value="com.aspectran.web.activity.WebTranslet"/>
		<setting name="transletImplementClass" value="com.aspectran.web.activity.WebTransletImpl"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
		<setting name="beanProxyMode" value="cglib"/>
		<setting name="classPathes">
			WEB-INF/classes
			WEB-INF/classes/lib
		</setting>
	</settings>
	
	<aspect id="defaultRequestRule">
		<joinpoint scope="request"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="multipart.maxRequestSize" value="10M"/>
			<setting name="multipart.temporaryFilePath" value="/d:/"/>
			<setting name="multipart.allowedFileExtensions" value="gif;jpg;png"/>
			<setting name="multipart.deniedFileExtensions" value="php;jsp;sh;bat"/>
		</settings>
		<!-- 
		<before>
			<action id="xml" bean="common.action.a1" method="testXmlAction">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</before>
		<after>
			<action id="xml" bean="common.action.a1" method="testXmlAction">
				<properties>
					<item name="variable1">error</item>
					<item name="variable2">0001</item>
				</properties>
			</action>
		</after>
		-->
	</aspect>
	
	<aspect id="frontRequestRule">
		<joinpoint scope="request">
			<pointcut>/front/*</pointcut>
		</joinpoint>
		<advice>
			<before>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
			</before>
			<after>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
			</after>
		</advice>
	</aspect>

	<bean id="jspViewDispatcher" class="com.aspectran.web.view.JspViewDispatcher" scope="singleton"/>

	<aspect id="defaultResponseRule">
		<joinpoint scope="response"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="defaultContentType" value="text/html"/>
			<setting name="viewDispatcher" value="jspViewDispatcher"/>
		</settings>
	</aspect>

	<aspect id="error">
		<joinpoint/>
		<advice>
			<exceptionRaized>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
				<responseByContentType exceptionType="com.aspectran.test.web.LoginFailedException">
					<dispatch contentType="text/html">
						<template file="/WEB-INF/jsp/login.jsp"/>
					</dispatch>
					<transform contentType="text/json">
						<template>{}</template>
					</transform>
				</responseByContentType>
				<responseByContentType>
					<dispatch contentType="text/html">
						<template file="/WEB-INF/jsp/error.jsp"/>
					</dispatch>
					<!-- forward contentType="text/html" translet="error"/ -->
					<transform contentType="text/plain">
						<template>
							오류 발생!
							오류 발생!
						</template>
					</transform>
					<transform contentType="text/xml">
						<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
							<properties>
								<item name="variable1">error</item>
								<item name="variable2">0001</item>
							</properties>
						</action>
						<echo id="error3">
							<item name="code">0002</item>
							<item name="message">오류 발생!</item>
						</echo>
						<echo id="error1">
							<item type="map">
								<value name="code">0001</value>
								<value name="message">오류 발생!</value>
							</item>
						</echo>
						<echo id="error2">
							<item type="map">
								<value name="code">0002</value>
								<value name="message">오류 발생!</value>
							</item>
							<item type="map">
								<value name="code">0004</value>
								<value name="message">오류 발생!</value>
							</item>
						</echo>
					</transform>
				</responseByContentType>
				<defaultResponse>
					<redirect translet="error"/>
				</defaultResponse>
			</exceptionRaized>
		</advice>
	</aspect>

	<aspect id="bean1">
		<joinpoint>
			<pointcut>/front/*</pointcut>
		</joinpoint>
		<advice>
			<around>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
			</around>
		</advice>
	</aspect>

	<!--
		before: access logging
		after: error logging 
	-->
	<aspect id="logging">
		<joinpoint>
			<pointcut>@front.action1</pointcut>
		</joinpoint>
		<advice>
			<before>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
			</before>
			<after>
				<action id="xml" bean="common.action.a1" method="testXmlAction" hidden="true">
					<properties>
						<item name="variable1">error</item>
						<item name="variable2">0001</item>
					</properties>
				</action>
			</after>
		</advice>
	</aspect>

	<!--
		scheduler
	
	
  <property name="triggers">
   <list>
    <ref bean="SystemOutTestTrigger"/>
   </list>
  </property>
  <property name="quartzProperties">
   <props>
    <prop key="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</prop>
    <prop key="org.quartz.threadPool.threadCount">5</prop>
    <prop key="org.quartz.threadPool.threadPriority">4</prop>
    <prop key="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</prop>
    <prop key="org.quartz.jobStore.misfireThreshold">600000</prop>
   </props>
  </property>
 </bean>
	-->
	<bean class="org.quartz.impl.StdSchedulerFactory" scope="singleton">
		<constructor>
			<arguments>
				<item type="properties">
					<value name="org.quartz.scheduler.instanceName">DefaultQuartzScheduler</value>
					<value name="org.quartz.scheduler.rmi.export">false</value>
					<value name="org.quartz.scheduler.rmi.proxy">false</value>
					<value name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</value>
					<value name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</value>
					<value name="org.quartz.threadPool.threadCount">10</value>
					<value name="org.quartz.threadPool.threadPriority">5</value>
					<value name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</value>
					<value name="org.quartz.jobStore.misfireThreshold">60000</value>
					<value name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</value>
				</item>
			</arguments>
		</constructor>
	</bean>
	
	<aspect id="scheduler1" for="scheduler">
		<joinpoint>
			<pointcut type="simpleTrigger">
				startDelay: 500
				repleatInterval: 3000
				repeatCount: 10
			</pointcut>
		</joinpoint>
		<advice bean="schedulerFactory1">
			<job translet="/scheduler1/test1.job"/>
			<job translet="/scheduler1/test2.job"/>
		</advice>
	</aspect>
	<aspect id="scheduler2" for="scheduler">
		<joinpoint>
			<pointcut type="cronTrigger">* * 10 0</pointcut>
		</joinpoint>
		<advice bean="schedulerFactory1">
			<job translet="/scheduler1/test3.job"/>
			<job translet="/scheduler1/test4.job" disabled="true"/>
		</advice>
	</aspect>

	<!--
		Matching targets:
			request: reserved
			response: reserved
			bean: each time it is called
			translet: each time it is called
			action: each time it is called
		getAspectObject:
			a return object of <before> action.
	-->
	<aspect id="sqlmap">
		<joinpoint scope="content">
			<pointcut>
				+(/front/a/*)
				-(/front/a/A*)
			</pointcut>
		</joinpoint>
		<advice bean="com.aspectran.support.orm.ibatis.SqlMapClientTransactionAdvice">
			<before>
				<action method="begin"/>
			</before>
			<finally>
				<action method="commit"/>
			</finally>
		</advice>
	</aspect>
	
	<bean id="a.*" class="com.**.*Aspectran*" scope="singleton"/>
	<bean id="b.*" class="com.aspectran.test.**.Sample*Test*Bean" scope="singleton"/>

	<import resource="aspectran/translets/sample.xml"/>
	
</aspectran>
