=== aspectran/aspectran/src/main/resources/com/aspectran/core/context/builder/xml/dtd/aspectran-3.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 3.0

  Copyright 2008-2016 Juho Jeong

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 3.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-3.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 3.0//EN"
                             "http://aspectran.github.io/dtd/aspectran-3.dtd">
-->

<!ELEMENT aspectran (
    description?,
    (settings? | environment* | typeAliases* | aspect* | bean* | template* | schedule* | translet* | import*)*
  )
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT settings (#PCDATA | setting)*>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #IMPLIED
>

<!ELEMENT environment (#PCDATA | properties)*>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT aspect (description?, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  type   (session | translet | bean) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | action)>
<!ELEMENT after   (headers | echo | action)>
<!ELEMENT around  (action)>
<!ELEMENT finally (thrown?, (headers | echo | action))>

<!ELEMENT exception (description?, thrown*)>

<!ELEMENT thrown ((headers | echo | action)? | transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST thrown
  type CDATA #IMPLIED
>

<!ELEMENT bean (description?, filter?, constructor?, properties?)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session | application) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT constructor (arguments?)>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT schedule (description?, trigger, scheduler)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT scheduler (job*)>
<!ATTLIST scheduler
  bean    CDATA #REQUIRED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
    (description?, request?, (action? | include? | echo? | headers?)*, (transform | dispatch | redirect | forward)?, exception?) |
    (description?, request?, (action? | include? | echo? | headers?)*, response*, exception?) |
    (description?, request?, content*, contents?, (transform | dispatch | redirect | forward)?, exception?) |
    (description?, request?, content*, contents?, response*, exception?)
  )>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters?, attributes?)>
<!ATTLIST request
  method            CDATA #IMPLIED
  characterEncoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
>

<!ELEMENT content (action? | include? | echo? | headers?)*>
<!ATTLIST content
  name      CDATA #IMPLIED
  omittable (true | false) #IMPLIED
  hidden    (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #IMPLIED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (attributes?)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | attributes | item)*>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT headers (#PCDATA | item)*>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)>
<!ATTLIST response
  name              CDATA #IMPLIED
  characterEncoding CDATA #IMPLIED
>

<!ELEMENT transform ((action? | include? | echo? | headers?)*, template?)>
<!ATTLIST transform
  type              CDATA #IMPLIED
  contentType       CDATA #IMPLIED
  template          CDATA #IMPLIED
  characterEncoding CDATA #IMPLIED
  default           (true | false) #IMPLIED
  pretty            (true | false) #IMPLIED
>

<!ELEMENT dispatch (action? | include? | echo? | headers?)*>
<!ATTLIST dispatch
  name              CDATA #REQUIRED
  dispatcher        CDATA #IMPLIED
  contentType       CDATA #IMPLIED
  characterEncoding CDATA #IMPLIED
  default           (true | false) #IMPLIED
>

<!ELEMENT redirect ((action? | include? | echo? | headers?)*, parameters*)>
<!ATTLIST redirect
  contentType           CDATA #IMPLIED
  target                CDATA #REQUIRED
  excludeNullParameters CDATA #IMPLIED
  default               (true | false) #IMPLIED
>

<!ELEMENT url (#PCDATA)>

<!ELEMENT forward ((action? | include? | echo? | headers?)*, attributes?)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #IMPLIED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  fileType (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

<!ELEMENT parameters (#PCDATA | item)*>
<!ELEMENT attributes (#PCDATA | item)*>
<!ELEMENT properties (#PCDATA | item)*>
<!ELEMENT arguments  (#PCDATA | item)*>

<!ELEMENT item (#PCDATA | value | ref | null)*>
<!ATTLIST item
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  type         (single | array | list | map | set | properties) #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipartFile) #IMPLIED
  defaultValue CDATA #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | ref | null)*>
<!ATTLIST value
  name    CDATA #IMPLIED
>

<!ELEMENT ref EMPTY>
<!ATTLIST ref
  bean      CDATA #IMPLIED
  parameter CDATA #IMPLIED
  attribute CDATA #IMPLIED
  property  CDATA #IMPLIED
>

<!ELEMENT null EMPTY>

=== aspectran/aspectran/src/test/resources/config/embedded/embedded-mode-test-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 2.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-3.dtd">

<aspectran>
	
	<description>
		Aspectran configuration for embedded mode for tests
	</description>

	<bean scan="com.aspectran.embedded.*Bean" mask="com.aspectran.embedded.*"/>
	
	<bean scan="com.aspectran.embedded.*Configuration" mask="com.aspectran.embedded.*"/>

	<bean id="freemarkerConfigurationFactory" class="com.aspectran.core.context.template.engine.freemarker.FreeMarkerConfigurationFactoryBean">
		<properties>
			<item name="freemarkerSettings" type="properties">
				<value name="incompatible_improvements">2.3.23</value>
				<value name="template_exception_handler">rethrow</value>
				<value name="default_encoding">UTF-8</value>
				<value name="number_format">0.####</value>
			</item>
			<item name="trimDirectives" valueType="parameters">
				directive: {
					name: trim
				}
				directive: {
					name: where
					prefix: "WHERE "
					deprefixes: [
						"and "
						"and\t"
						"or "
						"or\t"
					]
				}
				directive: {
					name: set
					prefix: "SET "
					desuffixes: ","
				}
			</item>
		</properties>
	</bean>

	<bean id="freemarker" class="com.aspectran.core.context.template.engine.freemarker.FreeMarkerTemplateEngine">
		<constructor>
			<arguments>
				<item><ref bean="freemarkerConfigurationFactory"/></item>
			</arguments>
		</constructor>
	</bean>

	<translet name="echo">
		<request>
			<parameters>
				<item name="input-1">${input-1:12345}</item>
				<item name="input-2">${input-2:67890}</item>
			</parameters>
		</request>
		<transform type="transform/text" contentType="text/plain">
			<template>
				Using Builtin Token Template Engine
				-------------------------------------
				input-1: ${input-1}
				input-2: ${input-2}
			</template>
		</transform>
	</translet>

	<template id="echo" engine="builtin">
		ID: ${id}
		Name: ${name}
		Email: ${email}
	</template>

	<template id="selectQuery" engine="freemarker">
		<![CDATA[
		SELECT
			'${name}' as name,
			'${email}' as email
		FROM table1
		<@directive.where>
			<#if id?has_content>
			AND id = :id
			</#if>
			<#if name?has_content>
			AND name = :name
			</#if>
			<#if email?has_content>
			AND email = :email
			</#if>
		</@directive.where>
		ORDER BY name
		]]>
	</template>

	<template id="updateQuery" engine="freemarker">
		<![CDATA[
		UPDATE table1
		<@directive.set>
			<#if name??>
			name = :name,
			</#if>
			<#if email??>
			email = :email,
			</#if>
			<#if id??>
			id = :id,
			</#if>
		</@directive.set>
		WHERE id = :id
		]]>
	</template>

</aspectran>

=== aspectran/aspectran/src/test/resources/config/aop/simple-aop-test-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 2.0//EN"
                           "http://aspectran.github.io/dtd/aspectran-3.dtd">

<aspectran>
	
	<description>
		Aspectran's AOP is simple and powerful.
	</description>

	<bean scan="com.aspectran.aop.*Action"/>

	<bean id="simpleAopTestAdvice" class="com.aspectran.aop.SimpleAopTestAdvice"/>

	<aspect id="testAop">
		<description>
			요청 URI가 "/example/"로 시작하고,
			helloworld.HelloWorldAction 빈에서 echo, helloWorld, counting 메쏘드 호출 전 후로
			환영인사와 작별인사를 건넵니다.
		</description>
		<joinpoint type="translet">
			pointcut: {
				+: /aop/test/*
			}
		</joinpoint>
		<advice bean="simpleAopTestAdvice">
			<before>
				<action method="begin"/>
			</before>
			<after>
				<action method="end"/>
			</after>
			<finally>
				<thrown>
					<action method="thrown"/>
				</thrown>
				<action method="close"/>
			</finally>
		</advice>
		<exception>
			<thrown>
				<action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
			</thrown>
		</exception>
	</aspect>

</aspectran>
