=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-6.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 6.0

  Copyright 2008-2020 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-6.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
          "http://aspectran.github.io/dtd/aspectran-6.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | template | schedule | translet | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, properties+)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT around  (action | invoke)>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, arguments*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameters*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name      CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (arguments*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (arguments*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  secret       (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | bean)*>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/demo/app/config/web/web-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        An Aspectran configuration for the Web Application.
        Note that names of translets that match the request URI
        always start with a forward slash (/).
    </description>

    <bean id="jspViewDispatcher" class="com.aspectran.web.support.view.JspViewDispatcher">
        <description>
            Register a JSP View Dispatcher.
        </description>
        <properties>
            <item name="prefix">/WEB-INF/jsp/</item>
            <item name="suffix">.jsp</item>
        </properties>
    </bean>

    <aspect id="transletSettings">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint target="translet"/>
        <settings>
            <setting name="characterEncoding" value="utf-8"/>
            <setting name="viewDispatcher" value="jspViewDispatcher"/>
            <setting name="indentString" value="  "/>
        </settings>
    </aspect>

    <append file="/config/web/home/main.xml"/>
    <append file="/config/web/examples/hello-world.xml"/>
    <append file="/config/web/examples/gs-rest-service.xml"/>
    <append file="/config/web/examples/file-upload.xml"/>
    <append file="/config/web/terminal/translet-interpreter.xml"/>

</aspectran>

=== aspectran/aspectran/demo/app/config/web/apm/apm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <settings>
        <setting name="transletNamePrefix" value="/apm"/>
    </settings>

    <translet name="/">
        <echo id="page">
            <item name="headline">Application Performance Monitoring</item>
            <item name="teaser">Analyze application logging messages to visually express the frequency of web requests based on the user's session usage history.</item>
            <item name="include">apm/apm</item>
            <item name="style">fluid</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

    <bean id="logTailerManager" class="com.aspectran.demo.apm.log.LogTailerManager">
        <arguments>
            <item>#{class:com.aspectran.demo.apm.log.LogtailEndpoint}</item>
            <item type="array">
                <bean class="com.aspectran.demo.apm.log.LogTailer">
                    <arguments>
                        <item>app-log</item>
                        <item>#{basePath}/logs/app.log</item>
                    </arguments>
                </bean>
            </item>
        </arguments>
    </bean>

</aspectran>

=== aspectran/aspectran/embed/src/test/resources/config/scheduler/scheduler-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <settings>
        <setting name="transletNameSuffix" value=".job"/>
    </settings>

    <bean id="*" scan="com.aspectran.embed.sample.**.*Advice" mask="com.aspectran.embed.**.*"/>
    <bean id="*" scan="com.aspectran.embed.service.**.*Advice" mask="com.aspectran.embed.**.*"/>
    <bean id="*" scan="com.aspectran.embed.sample.**.*Activity" mask="com.aspectran.embed.**.*"/>
    <bean id="*" scan="com.aspectran.embed.service.**.*Activity" mask="com.aspectran.embed.**.*"/>

    <bean id="defaultScheduler1" class="com.aspectran.core.scheduler.support.QuartzSchedulerFactoryBean" lazyInit="true">
        <properties>
            <item type="properties" name="quartzProperties">
                <entry name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-1</entry>
                <entry name="org.quartz.scheduler.rmi.export">false</entry>
                <entry name="org.quartz.scheduler.rmi.proxy">false</entry>
                <entry name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</entry>
                <entry name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</entry>
                <entry name="org.quartz.threadPool.threadCount">10</entry>
                <entry name="org.quartz.threadPool.threadPriority">5</entry>
                <entry name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</entry>
                <entry name="org.quartz.jobStore.misfireThreshold">60001</entry>
                <entry name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</entry>
            </item>
        </properties>
    </bean>

    <bean id="schedulerFactory" class="org.quartz.impl.StdSchedulerFactory" lazyInit="true">
        <arguments>
            <item type="properties">
                <entry name="org.quartz.scheduler.instanceName">AspectranQuartzScheduler-2</entry>
                <entry name="org.quartz.scheduler.rmi.export">false</entry>
                <entry name="org.quartz.scheduler.rmi.proxy">false</entry>
                <entry name="org.quartz.scheduler.wrapJobExecutionInUserTransaction">false</entry>
                <entry name="org.quartz.threadPool.class">org.quartz.simpl.SimpleThreadPool</entry>
                <entry name="org.quartz.threadPool.threadCount">10</entry>
                <entry name="org.quartz.threadPool.threadPriority">5</entry>
                <entry name="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread">true</entry>
                <entry name="org.quartz.jobStore.misfireThreshold">60000</entry>
                <entry name="org.quartz.jobStore.class">org.quartz.simpl.RAMJobStore</entry>
            </item>
        </arguments>
    </bean>

    <bean id="defaultScheduler2" factoryBean="schedulerFactory" factoryMethod="getScheduler" lazyInit="true"/>

    <schedule id="scheduler1">
        <scheduler bean="defaultScheduler1">
            <trigger type="simple">
                intervalInSeconds: 1
                repeatCount: 1
            </trigger>
        </scheduler>
        <job translet="job1.job"/>
    </schedule>

    <schedule id="scheduler2">
        <scheduler bean="defaultScheduler2">
            <trigger type="simple">
                startDelaySeconds: 0
                intervalInSeconds: 1
                repeatCount: 1
            </trigger>
        </scheduler>
        <job translet="job2.job"/>
    </schedule>

    <translet name="job1">
        <action bean="sample.schedule.ScheduleActivity" method="delay">
            <arguments>
                <item valueType="long">1</item>
            </arguments>
        </action>
        <transform format="text" contentType="text/plain">
            <template>(1) Hello, World!</template>
        </transform>
    </translet>

    <translet name="job2">
        <action bean="sample.schedule.ScheduleActivity" method="delay">
            <arguments>
                <item valueType="long">2</item>
            </arguments>
        </action>
        <transform format="text" contentType="text/plain">
            <template>(2) Hello, World!</template>
        </transform>
    </translet>

</aspectran>

=== aspectran/aspectran/demo/app/config/web/skylark/skylark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        Skylark is a text-to-speech web application.
    </description>

    <settings>
        <setting name="transletNamePrefix" value="/skylark/"/>
    </settings>

    <translet name="/">
        <echo id="page">
            <item name="headline">Skylark Terminal</item>
            <item name="teaser">Skylark is a text to speech program that converts any written text into spoken words.</item>
            <item name="include">skylark/skylark</item>
            <item name="style">plate</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

    <append file="/config/web/skylark/tts/voices.xml"/>
    <append file="/config/web/skylark/tts/api-v0.xml"/>

</aspectran>
