=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-6.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 6.0

  Copyright 2008-2020 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-6.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
          "http://aspectran.github.io/dtd/aspectran-6.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | template | schedule | translet | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, properties+)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT around  (action | invoke)>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, arguments*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameters*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name      CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (arguments*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (arguments*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  secret       (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | bean)*>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/demo/app/config/web/terminal/terminal-commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <translet name="/hello">
        <parameters>
            <item name="email" mandatory="true">${id}@${domain}</item>
            <item name="password" mandatory="true" secret="true"/>
        </parameters>
        <attributes>
            <item name="attr1" mandatory="true">${id}@${domain}</item>
            <item name="attr2" mandatory="true" secret="true">${password}</item>
            <item name="attr3" mandatory="true">${attr3}</item>
            <item name="attr4" mandatory="true">${attr4}</item>
        </attributes>
        <transform type="text">
            <template style="apon">
                |------------------------------------------------
                |The parameters you entered are:
                |   email: ${email}
                |   password: ${password}
                |The attributes you entered are:
                |   attr1: @{attr1}
                |   attr2: @{attr2}
                |   attr3: @{attr3}
                |   attr4: @{attr4}
                |------------------------------------------------
            </template>
        </transform>
    </translet>

</aspectran>

=== aspectran/aspectran/with-jetty/src/test/resources/config/jetty/jetty-config.xml
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        An Aspectran configuration for Embedded Jetty Server.
    </description>

    <environment>
        <properties>
            <item name="jetty.startup" value="false" valueType="boolean"/>
            <item name="jetty.server.port" value="8099" valueType="int"/>
            <item name="jetty.server.minThreads" value="1" valueType="int"/>
            <item name="jetty.server.maxThreads" value="5" valueType="int"/>
            <item name="jetty.session.dataStoreDir" value="#{basePath}/temp/_sessions/jetty"/>
            <item name="jetty.gzip.minGzipSize" value="2048" valueType="int"/>
            <item name="jetty.gzip.inflateBufferSize" value="0" valueType="int"/>
            <item name="jetty.gzip.deflaterPoolCapacity" value="-1" valueType="int"/>
            <item name="jetty.gzip.syncFlush" value="false" valueType="boolean"/>
            <item name="jetty.gzip.includedMethodList" value="GET"/>
            <item name="jetty.gzip.excludedMethodList" value=""/>
        </properties>
    </environment>

    <bean id="jetty.server" class="com.aspectran.jetty.JettyServer">
        <arguments>
            <item name="threadPool">#{jetty.threadPool}</item>
        </arguments>
        <properties>
            <item name="autoStart">%{jetty.startup}</item>
            <item name="connectors" type="array">
                <value>#{jetty.connector}</value>
            </item>
            <item name="handler">#{jetty.mainHandler}</item>
        </properties>
    </bean>

    <bean id="jetty.threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool" scope="prototype">
        <properties>
            <item name="minThreads" value="%{jetty.server.minThreads}"/>
            <item name="maxThreads" value="%{jetty.server.maxThreads}"/>
        </properties>
    </bean>

    <bean id="jetty.connector" class="org.eclipse.jetty.server.ServerConnector" scope="prototype">
        <arguments>
            <item>#{jetty.server}</item>
        </arguments>
        <properties>
            <item name="port" value="%{jetty.server.port}"/>
        </properties>
    </bean>

    <bean id="jetty.mainHandler" class="org.eclipse.jetty.server.handler.HandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <value>#{jetty.gzipHandler}</value>
                <!--<value>#{jetty.requestLog}</value>-->
            </item>
        </properties>
    </bean>

    <bean id="jetty.gzipHandler" class="org.eclipse.jetty.server.handler.gzip.GzipHandler" scope="prototype">
        <properties>
            <item name="minGzipSize" valueType="int">%{jetty.gzip.minGzipSize}</item>
            <item name="inflateBufferSize" valueType="int">%{jetty.gzip.inflateBufferSize}</item>
            <item name="deflaterPoolCapacity" valueType="int">%{jetty.gzip.deflaterPoolCapacity}</item>
            <item name="syncFlush" valueType="boolean">%{jetty.gzip.syncFlush}</item>
            <item name="includedMethodList">%{jetty.gzip.includedMethodList}</item>
            <item name="excludedMethodList">%{jetty.gzip.excludedMethodList}</item>
            <item name="handler">#{jetty.handlerCollection}</item>
        </properties>
    </bean>

    <bean id="jetty.handlerCollection" class="org.eclipse.jetty.server.handler.HandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <value>#{jetty.contexts}</value>
                <value>#{jetty.defaultHandler}</value>
            </item>
        </properties>
    </bean>

    <bean id="jetty.contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <value>#{jetty.contexts.root}</value>
            </item>
        </properties>
    </bean>

    <bean id="jetty.contexts.root" class="com.aspectran.jetty.JettyWebAppContext" scope="prototype">
        <properties>
            <item name="contextPath" value="/"/>
            <item name="war" value="#{basePath}/webroot"/>
            <item name="persistTempDirectory" value="true" valueType="boolean"/>
            <item name="defaultsDescriptor" value="config/jetty/webdefault.xml"/>
            <item name="sessionHandler">#{jetty.sessionHandler}</item>
            <item name="webSocketEnabled" valueType="boolean">false</item>
            <item name="derived" valueType="boolean">true</item>
        </properties>
    </bean>

    <bean id="jetty.sessionHandler" class="com.aspectran.jetty.JettySessionHandler" scope="prototype">
        <properties>
            <item name="sessionDataStore">#{jetty.sessionDataStoreFactory}</item>
        </properties>
    </bean>

    <bean id="jetty.sessionDataStoreFactory" class="org.eclipse.jetty.server.session.FileSessionDataStoreFactory" scope="prototype">
        <properties>
            <item name="storeDir" valueType="file">%{jetty.session.dataStoreDir}</item>
            <item name="deleteUnrestorableFiles" valueType="boolean">true</item>
        </properties>
    </bean>

    <bean id="jetty.defaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler" scope="prototype"/>

    <bean id="jetty.requestLog" class="org.eclipse.jetty.server.handler.RequestLogHandler" scope="prototype">
        <properties>
            <item name="requestLog">#{jetty.customRequestLog}</item>
        </properties>
    </bean>

    <bean id="jetty.customRequestLog" class="org.eclipse.jetty.server.CustomRequestLog" scope="prototype">
        <arguments>
            <item>#{jetty.asyncRequestLogWriter}</item>
            <item>#{field:org.eclipse.jetty.server.CustomRequestLog^EXTENDED_NCSA_FORMAT}</item>
        </arguments>
    </bean>

    <bean id="jetty.asyncRequestLogWriter" class="org.eclipse.jetty.server.AsyncRequestLogWriter" scope="prototype">
        <arguments>
            <item>#{basePath}/logs/jetty-yyyy_mm_dd.request.log</item>
        </arguments>
        <properties>
            <item name="filenameDateFormat">yyyy_MM_dd</item>
            <item name="retainDays" valueType="int">90</item>
            <item name="append" valueType="boolean">true</item>
            <item name="timeZone">GMT+9</item>
        </properties>
    </bean>

</aspectran>

=== aspectran/aspectran/demo/app/config/web/examples/gs-rest-service.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        A collection of Translets for the Restful Web Service example.
    </description>

    <translet name="/examples/gs-rest-service/">
        <echo id="page">
            <item name="headline">Building a RESTful Web Service</item>
            <item name="teaser">
                A sample page that uses RESTful web services using HTTP support methods such as
                GET, PUT, POST, and DELETE.
            </item>
            <item name="include">examples/gs-rest-service</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

</aspectran>

=== aspectran/aspectran/shell/src/test/resources/config/shell/shell-test-root-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description style="apon">
        |Commands that can run the examples:
        |   hello     Runs the helloWorld() method of the sampleAction bean and prints the returned value to the console.
        |   echo      It accepts parameters and print them to the console.
        |   login     It accepts parameters used for login and print them to the console.
        |   chpw      It accepts parameters for changing the password and print them to the console.
        |   free      It uses the Freemarker template engine to output the values of the input parameters to the console.
        |   select    This example generates a simple SQL SELECT statement using the Freemarker template engine.
        |   update    This example generates a simple SQL UPDATE statement using the Freemarker template engine.
        |
    </description>

    <bean id="sampleAction" class="com.aspectran.shell.sample.SampleAction">
        <description>
            Defines one sample action that contains the helloWorld method.
        </description>
    </bean>

    <bean id="sampleAdvice" class="com.aspectran.shell.sample.SampleAdvice">
        <description>
            Action Method 실행 전 후에 주입할 Advice Action Method를 가지고 있는
            singleton 스코프를 가지는 Bean을 정의합니다.
        </description>
    </bean>

    <bean id="currentActivityData" class="com.aspectran.core.support.CurrentActivityDataFactoryBean" scope="request"/>

    <aspect id="sampleAdviceAspect">
        <description>
            sampleAction Bean의 helloWorld 메쏘드를 실행하는 Translet이 발견되면,
            해당 Translet의 실행 전에는 sampleAdvice Bean의 welcome 메쏘드를 실행하고,
            해당 Translet의 실행 후에는 sampleAdvice Bean의 goodbye 메쏘드를 실행합니다.
        </description>
        <joinpoint target="translet">
            pointcut: {
                +: hello@sampleAction^helloWorld
            }
        </joinpoint>
        <advice bean="sampleAdvice">
            <before>
                <action method="welcome"/>
            </before>
            <after>
                <action method="goodbye"/>
            </after>
        </advice>
    </aspect>

    <translet name="hello">
        <description>
            sampleAction 빈에서 helloWorld 메쏘드를 실행합니다.
            helloWorld 메쏘드가 반환하는 "Hello, World." 문자열을 텍스트 형식의 컨텐츠로 응답합니다.
        </description>
        <transform type="transform/text">
            <action id="helloData" bean="sampleAction" method="helloWorld"/>
        </transform>
    </translet>

    <translet name="echo1">
        <description style="apon">
            |It accepts parameters and print them to the console.
        </description>
        <parameters>
            <item name="param1" mandatory="false"/>
            <item name="param2" mandatory="true"/>
        </parameters>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The parameters you entered are:
                |   param1: ${param1}
                |   param2: ${param2}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo2">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="param1" mandatory="true">${prefix} - 1</item>
            <item name="param2">${prefix} - 2</item>
            <item name="param3">${prefix} - 3</item>
        </parameters>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The parameters you entered are:
                |   param1: ${param1}
                |   param2: ${param2}
                |   param3: ${param3}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo3">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="param1">first ${param1:12345}</item>
            <item name="param2">second ${param2:67890}</item>
            <item name="param3" mandatory="true">third ${param3-1} and ${param3-2}</item>
        </parameters>
        <attributes>
            <item name="attr1">fourth ${param4}</item>
        </attributes>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The input parameters and attributes are as follows:
                |   param1: ${param1}
                |   param2: ${param2}
                |   param3: ${param3}
                |   attr1: @{attr1}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo ${text}">
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |${text}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="login">
        <description style="apon">
            |
            |   It accepts parameters used for login and print them to the console.
            |
        </description>
        <parameters>
            <item name="id" mandatory="true"/>
            <item name="email" mandatory="true">${id}@${domain}</item>
            <item name="password" security="true" defaultValue="(none)"/>
        </parameters>
        <transform type="transform/text">
            <template style="apon">
                |-------------------------------------------------------------------------
                |You have entered the following parameters for login:
                |   email: ${email}
                |   password: ${password}
                |-------------------------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="chpw">
        <description style="apon">
            |
            |   It accepts parameters for changing the password and print them to the console.
            |
        </description>
        <parameters>
            <item name="email">${emailId}@${emailDomain}</item>
            <item name="password" security="true"/>
            <item name="confirmPassword" security="true"/>
        </parameters>
        <transform type="transform/text">
            <template style="apon">
                |------------------------------------------------------------------------------------
                |You have entered the following parameters for changing the password:
                |   email: ${email}
                |   password: ${password}
                |   confirm password: ${confirmPassword}
                |------------------------------------------------------------------------------------
            </template>
        </transform>
    </translet>

    <append resource="config/shell/freemarker-translets.xml"/>

</aspectran>
