=== aspectran/aspectran/core/src/main/resources/com/aspectran/core/context/rule/parser/xml/dtd/aspectran-6.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XML DTD for the Aspectran Configuration File, Version 6.0

  Copyright 2008-2020 The Aspectran Project

  This DTD module is identified by the PUBLIC and SYSTEM identifiers:

  PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
  SYSTEM "http://aspectran.github.io/dtd/aspectran-6.dtd">

  XML documents that conform to this DTD should declare the following doctype:

  <!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
          "http://aspectran.github.io/dtd/aspectran-6.dtd">
-->

<!ELEMENT aspectran (
  description*,
  settings?,
  (typeAliases | environment | aspect | bean | template | schedule | translet | append)*
)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  profile CDATA #IMPLIED
  style   (apon | compact | compressed) #IMPLIED
>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting
  name    CDATA #REQUIRED
  value   CDATA #REQUIRED
>

<!ELEMENT typeAliases (typeAlias+)>
<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
  alias   CDATA #REQUIRED
  type    CDATA #REQUIRED
>

<!ELEMENT environment (description*, properties+)>
<!ATTLIST environment
  profile CDATA #IMPLIED
>

<!ELEMENT aspect (description*, joinpoint?, settings?, advice?, exception?)>
<!ATTLIST aspect
  id       ID #IMPLIED
  order    CDATA #IMPLIED
  isolated (true | false) #IMPLIED
  disabled (true | false) #IMPLIED
>

<!ELEMENT joinpoint (#PCDATA)>
<!ATTLIST joinpoint
  target  (activity | method) #IMPLIED
>

<!ELEMENT advice (before?, after?, around?, finally?)>
<!ATTLIST advice
  bean    CDATA #IMPLIED
>

<!ELEMENT before  (headers | echo | (action | invoke))>
<!ELEMENT after   (headers | echo | (action | invoke))>
<!ELEMENT around  (action | invoke)>
<!ELEMENT finally (thrown?, (headers | echo | (action | invoke)))>

<!ELEMENT exception (description*, thrown+)>

<!ELEMENT thrown ((headers | echo | (action | invoke)?)?, (transform | dispatch | redirect)*)>
<!ATTLIST thrown
  type    CDATA #IMPLIED
>

<!ELEMENT bean (description*, filter?, arguments*, properties*)>
<!ATTLIST bean
  id            CDATA #IMPLIED
  class         CDATA #IMPLIED
  scan          CDATA #IMPLIED
  mask          CDATA #IMPLIED
  factoryBean   CDATA #IMPLIED
  factoryMethod CDATA #IMPLIED
  initMethod    CDATA #IMPLIED
  destroyMethod CDATA #IMPLIED
  scope         (singleton | prototype | request | session) #IMPLIED
  singleton     (true | false) #IMPLIED
  lazyInit      (true | false) #IMPLIED
  lazyDestroy   (true | false) #IMPLIED
  important     (true | false) #IMPLIED
>

<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
  class   CDATA #IMPLIED
>

<!ELEMENT schedule (description*, scheduler, job*)>
<!ATTLIST schedule
  id      ID #IMPLIED
>

<!ELEMENT scheduler (trigger)>
<!ATTLIST scheduler
  bean    CDATA #IMPLIED
>

<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
  type    CDATA #IMPLIED
>

<!ELEMENT job EMPTY>
<!ATTLIST job
  translet CDATA #REQUIRED
  disabled (true | false) #IMPLIED
>

<!ELEMENT translet (
  description*,
  (request? | (parameters*, attributes*)),
  ((contents | content)? | (choose | headers | echo | action | include)*),
  (response* | (transform | dispatch | forward | redirect)?),
  exception?
)>
<!ATTLIST translet
  name    CDATA #REQUIRED
  scan    CDATA #IMPLIED
  mask    CDATA #IMPLIED
  method  CDATA #IMPLIED
>

<!ELEMENT request (parameters*, attributes*)>
<!ATTLIST request
  method   CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT contents (content*)>
<!ATTLIST contents
  name      CDATA #IMPLIED
>

<!ELEMENT content (choose | headers | echo | action | include)*>
<!ATTLIST content
  name      CDATA #IMPLIED
>

<!ELEMENT choose (when*, otherwise?)>

<!ELEMENT when ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST when
  test    CDATA #IMPLIED
>

<!ELEMENT otherwise ((headers | echo | action | include | choose)*, (transform | dispatch | forward | redirect)?)>

<!ELEMENT headers (item*)>
<!ATTLIST headers
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT echo (item*)>
<!ATTLIST echo
  id      CDATA #IMPLIED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT action (arguments*, properties*)>
<!ATTLIST action
  id      CDATA #IMPLIED
  bean    CDATA #REQUIRED
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT invoke (arguments*, properties*)>
<!ATTLIST invoke
  method  CDATA #REQUIRED
  hidden  (true | false) #IMPLIED
>

<!ELEMENT include (parameters*, attributes*)>
<!ATTLIST include
  id       CDATA #IMPLIED
  translet CDATA #REQUIRED
  method   CDATA #IMPLIED
  hidden   (true | false) #IMPLIED
>

<!ELEMENT response ((choose | headers | echo | action | include)*, (transform | dispatch | forward | redirect)?)>
<!ATTLIST response
  name     CDATA #IMPLIED
  encoding CDATA #IMPLIED
>

<!ELEMENT transform (template?)>
<!ATTLIST transform
  format      CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
  pretty      (true | false) #IMPLIED
>

<!ELEMENT dispatch EMPTY>
<!ATTLIST dispatch
  name        CDATA #REQUIRED
  dispatcher  CDATA #IMPLIED
  contentType CDATA #IMPLIED
  encoding    CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT forward (attributes*)>
<!ATTLIST forward
  contentType CDATA #IMPLIED
  translet    CDATA #REQUIRED
  method      CDATA #IMPLIED
  default     (true | false) #IMPLIED
>

<!ELEMENT redirect (parameters*)>
<!ATTLIST redirect
  contentType            CDATA #IMPLIED
  path                   CDATA #REQUIRED
  encoding               CDATA #IMPLIED
  excludeNullParameters  (true | false) #IMPLIED
  excludeEmptyParameters (true | false) #IMPLIED
  default                (true | false) #IMPLIED
>

<!ELEMENT parameters (item*)>
<!ATTLIST parameters
  profile CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>
<!ATTLIST attributes
  profile CDATA #IMPLIED
>

<!ELEMENT properties (item*)>
<!ATTLIST properties
  profile CDATA #IMPLIED
>

<!ELEMENT arguments (item*)>
<!ATTLIST arguments
  profile CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | entry | bean)*>
<!ATTLIST item
  type         (single | array | list | map | set | properties) #IMPLIED
  name         CDATA #IMPLIED
  value        CDATA #IMPLIED
  valueType    (string | int | long | float | double | boolean | parameters | file | multipart-file | bean) #IMPLIED
  tokenize     (true | false) #IMPLIED
  mandatory    (true | false) #IMPLIED
  secret       (true | false) #IMPLIED
>

<!ELEMENT value (#PCDATA | bean)*>

<!ELEMENT entry (#PCDATA | bean)*>
<!ATTLIST entry
  name     CDATA #IMPLIED
  value    CDATA #IMPLIED
  tokenize (true | false) #IMPLIED
>

<!ELEMENT template (#PCDATA)>
<!ATTLIST template
  id       CDATA #IMPLIED
  engine   CDATA #IMPLIED
  style    (apon | compact | compressed) #IMPLIED
  name     CDATA #IMPLIED
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  encoding CDATA #IMPLIED
  noCache  (true | false) #IMPLIED
>

<!ELEMENT append EMPTY>
<!ATTLIST append
  file     CDATA #IMPLIED
  resource CDATA #IMPLIED
  url      CDATA #IMPLIED
  format   (xml | apon) #IMPLIED
  profile  CDATA #IMPLIED
>

=== aspectran/aspectran/demo/app/config/server/jetty/jetty-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        An Aspectran configuration for Embedded Jetty Server.
    </description>

    <environment>
        <properties>
            <item name="jetty.startup" value="true" valueType="boolean"/>
            <item name="jetty.server.port" value="8080" valueType="int"/>
            <item name="jetty.server.minThreads" value="3" valueType="int"/>
            <item name="jetty.server.maxThreads" value="10" valueType="int"/>
            <item name="jetty.session.dataStoreDir" value="#{basePath}/temp/sessions/jetty"/>
            <item name="jetty.gzip.minGzipSize" value="20000" valueType="int"/>
            <item name="jetty.gzip.inflateBufferSize" value="0" valueType="int"/>
            <item name="jetty.gzip.deflaterPoolCapacity" value="-1" valueType="int"/>
            <item name="jetty.gzip.syncFlush" value="false" valueType="boolean"/>
            <item name="jetty.gzip.includedMethodList" value="GET"/>
            <item name="jetty.gzip.excludedMethodList" value=""/>
        </properties>
    </environment>

    <bean id="jetty.server" class="com.aspectran.jetty.JettyServer">
        <arguments>
            <item name="threadPool">
                <bean class="org.eclipse.jetty.util.thread.QueuedThreadPool">
                    <properties>
                        <item name="minThreads">%{jetty.server.minThreads}</item>
                        <item name="maxThreads">%{jetty.server.maxThreads}</item>
                    </properties>
                </bean>
            </item>
        </arguments>
        <properties>
            <item name="autoStart">%{jetty.startup}</item>
            <item name="connectors" type="array">
                <bean class="org.eclipse.jetty.server.ServerConnector">
                    <arguments>
                        <item>#{jetty.server}</item>
                    </arguments>
                    <properties>
                        <item name="port">%{jetty.server.port}</item>
                    </properties>
                </bean>
            </item>
            <item name="handler">
                <bean class="org.eclipse.jetty.server.handler.HandlerCollection">
                    <properties>
                        <item name="handlers" type="array">
                            <value>#{jetty.gzipHandler}</value>
                            <value>#{jetty.requestLogHandler}</value>
                        </item>
                    </properties>
                </bean>
            </item>
        </properties>
    </bean>

    <bean id="jetty.gzipHandler" class="org.eclipse.jetty.server.handler.gzip.GzipHandler" scope="prototype">
        <properties>
            <item name="minGzipSize" valueType="int">%{jetty.gzip.minGzipSize}</item>
            <item name="inflateBufferSize" valueType="int">%{jetty.gzip.inflateBufferSize}</item>
            <item name="deflaterPoolCapacity" valueType="int">%{jetty.gzip.deflaterPoolCapacity}</item>
            <item name="syncFlush" valueType="boolean">%{jetty.gzip.syncFlush}</item>
            <item name="includedMethodList">%{jetty.gzip.includedMethodList}</item>
            <item name="excludedMethodList">%{jetty.gzip.excludedMethodList}</item>
            <item name="handler">#{jetty.handlerCollection}</item>
        </properties>
    </bean>

    <bean id="jetty.handlerCollection" class="org.eclipse.jetty.server.handler.HandlerCollection" scope="prototype">
        <properties>
            <item name="handlers" type="array">
                <bean class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
                    <properties>
                        <item name="handlers" type="array">
                            <bean class="com.aspectran.jetty.JettyWebAppContext">
                                <properties>
                                    <item name="contextPath">/</item>
                                    <item name="war">#{basePath}/webapps/root</item>
                                    <item name="persistTempDirectory" valueType="boolean">true</item>
                                    <item name="defaultsDescriptor">#{basePath}/config/server/jetty/webdefault.xml</item>
                                    <item name="sessionHandler">#{jetty.sessionHandler}</item>
                                    <item name="derived" valueType="boolean">true</item>
                                </properties>
                            </bean>
                        </item>
                    </properties>
                </bean>
                <bean class="org.eclipse.jetty.server.handler.DefaultHandler"/>
            </item>
        </properties>
    </bean>

    <bean id="jetty.sessionHandler" class="com.aspectran.jetty.JettySessionHandler" scope="prototype">
        <properties>
            <item name="sessionDataStore">
                <bean class="org.eclipse.jetty.server.session.FileSessionDataStoreFactory">
                    <properties>
                        <item name="storeDir" valueType="file">%{jetty.session.dataStoreDir}</item>
                        <item name="deleteUnrestorableFiles" valueType="boolean">true</item>
                    </properties>
                </bean>
            </item>
        </properties>
    </bean>

    <bean id="jetty.requestLogHandler" class="org.eclipse.jetty.server.handler.RequestLogHandler" scope="prototype">
        <properties>
            <item name="requestLog">
                <bean class="org.eclipse.jetty.server.CustomRequestLog">
                    <arguments>
                        <item>
                            <bean class="org.eclipse.jetty.server.AsyncRequestLogWriter">
                                <arguments>
                                    <item>#{basePath}/logs/jetty-yyyy_mm_dd.request.log</item>
                                </arguments>
                                <properties>
                                    <item name="filenameDateFormat">yyyy_MM_dd</item>
                                    <item name="retainDays" valueType="int">90</item>
                                    <item name="append" valueType="boolean">true</item>
                                    <item name="timeZone">GMT+9</item>
                                </properties>
                            </bean>
                        </item>
                        <item tokenize="false">%{client}a - %u %{yyyy-MM-dd HH:mm:ss ZZZ|GMT+9}t "%r" %s %O "%{Referer}i" "%{User-Agent}i"</item>
                    </arguments>
                </bean>
            </item>
        </properties>
    </bean>

</aspectran>

=== aspectran/aspectran/demo/app/config/web/terminal/translet-interpreter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.
    </description>

    <settings>
        <setting name="transletNamePrefix" value="/interpreter/"/>
    </settings>

    <translet name="/">
        <echo id="page">
            <item name="headline">Remote Command Shell</item>
            <item name="teaser">You can run translets with a command line interpreter implemented using the jQuery Terminal Emulator.</item>
            <item name="include">terminal/translet-interpreter</item>
            <item name="style">plate</item>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

    <!--<append file="/config/web/terminal/terminal-commands.xml"/>-->

</aspectran>

=== aspectran/aspectran/demo/app/config/web/examples/hello-world.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <translet name="/examples/hello-world">
        <echo id="page">
            <attributes>
                <item name="headline">Hello, World!</item>
                <item name="teaser">
                    This is the output of a JSP page that is part
                    of the HelloWorld application.
                </item>
                <item name="include">examples/hello-world</item>
            </attributes>
        </echo>
        <dispatch name="templates/default"/>
    </translet>

</aspectran>

=== aspectran/aspectran/embed/src/test/resources/config/aop/simple-aop-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description>
        Aspectran's AOP is simple and powerful.
    </description>

    <bean scan="com.aspectran.aop.*TestActivity"/>

    <bean scan="com.aspectran.aop.*TestBean"/>

    <bean scan="com.aspectran.aop.*Aspect"/>

    <bean id="simpleAopTestAdvice" class="com.aspectran.aop.SimpleAopTestAdvice"/>

    <aspect id="aspect01" order="1" disabled="false">
        <joinpoint>
            pointcut: {
                +: aop/test/*
            }
        </joinpoint>
        <advice bean="simpleAopTestAdvice">
            <before>
                <invoke method="begin"/>
            </before>
            <after>
                <invoke method="end"/>
            </after>
            <finally>
                <thrown>
                    <invoke method="thrown"/>
                </thrown>
                <invoke method="close"/>
            </finally>
        </advice>
        <exception>
            <thrown>
                <action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
            </thrown>
        </exception>
    </aspect>

    <bean id="instantActivityAopTestAdvice" class="com.aspectran.aop.InstantActivityAopTestAdvice"/>

    <aspect id="aspect03" order="1" disabled="false">
        <joinpoint>
            pointcut: {
                +: **@class:com.aspectran.aop.InstantActivityTestBean
            }
        </joinpoint>
        <advice bean="instantActivityAopTestAdvice">
            <before>
                <invoke method="begin"/>
            </before>
            <after>
                <invoke method="end"/>
            </after>
            <finally>
                <thrown>
                    <invoke method="thrown"/>
                </thrown>
                <invoke method="close"/>
            </finally>
        </advice>
        <exception>
            <thrown>
                <action bean="simpleAopTestAdvice" method="globalExceptionHandling"/>
            </thrown>
        </exception>
    </aspect>

</aspectran>

=== aspectran/aspectran/demo/app/config/web/examples/file-upload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <settings>
        <setting name="transletNamePattern" value="/examples/file-upload/*"/>
    </settings>

    <aspect id="transletSettingsForFileUpload">
        <description>
            Specifies the environment variables used during request and response processing.
        </description>
        <joinpoint target="translet">
            methods: [
                POST
            ]
            pointcut: {
                +: /examples/file-upload/files
            }
        </joinpoint>
        <settings>
            <setting name="multipartFormDataParser" value="imageFileUploader"/>
        </settings>
    </aspect>

    <bean id="imageFileUploader" class="com.aspectran.web.support.multipart.inmemory.MemoryMultipartFormDataParserFactoryBean">
        <description>
            Required to handle multi-part form data.
        </description>
        <properties>
            <item name="maxRequestSize" value="6M"/>
            <item name="maxFileSize" value="5M"/>
            <item name="allowedFileExtensions" value="jpg,jpeg,png,gif"/>
        </properties>
    </bean>

    <bean class="com.aspectran.demo.examples.upload.SimpleFileUploadAction">
        <properties>
            <item name="maxFiles" valueType="int">12</item>
        </properties>
    </bean>

    <translet name="/">
        <action id="files" bean="class:com.aspectran.demo.examples.upload.SimpleFileUploadAction" method="list"/>
        <dispatch name="templates/default">
            <echo id="page">
                <attributes>
                    <item name="headline">Uploading Files</item>
                    <item name="teaser">This guide walks you through the process of creating a server application that can receive HTTP multi-part file uploads.</item>
                    <item name="include">examples/file-upload</item>
                    <item name="maxFiles">#{class:com.aspectran.demo.examples.upload.SimpleFileUploadAction^maxFiles}</item>
                </attributes>
            </echo>
        </dispatch>
    </translet>

</aspectran>

=== aspectran/aspectran/shell-jline/src/test/resources/config/shell/jline/shell-test-root-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//ASPECTRAN//DTD Aspectran Configuration 6.0//EN"
        "http://aspectran.github.io/dtd/aspectran-6.dtd">
<aspectran>

    <description style="apon">
        |
        |Commands that can run the examples:
        |   hello     Runs the helloWorld() method of the sampleAction bean and prints the returned value to the console.
        |   echo      It accepts parameters and print them to the console.
        |   login     It accepts parameters used for login and print them to the console.
        |   chpw      It accepts parameters for changing the password and print them to the console.
        |   free      It uses the Freemarker template engine to output the values of the input parameters to the console.
        |   select    This example generates a simple SQL SELECT statement using the Freemarker template engine.
        |   update    This example generates a simple SQL UPDATE statement using the Freemarker template engine.
        |
    </description>

    <bean id="sampleAction" class="com.aspectran.shell.jline.sample.SampleAction">
        <description>
            Defines one sample action that contains the helloWorld method.
        </description>
    </bean>

    <bean id="sampleAdvice" class="com.aspectran.shell.jline.sample.SampleAdvice">
        <description>
            Defines the Advice Bean that has the Advice Method to be injected before and after the Action Method.
        </description>
    </bean>

    <aspect id="sampleAdviceAspect">
        <description>
            If a Translet that executes the helloWorld method of the sampleAction bean is found,
            executes the welcome() method of the sampleAdvice bean before executing the translet,
            and executes the goodbye() method of the sampleAdvice bean after executing the translet.
        </description>
        <joinpoint target="translet">
            pointcut: {
                +: hello@sampleAction^helloWorld
            }
        </joinpoint>
        <advice bean="sampleAdvice">
            <before>
                <action method="welcome"/>
            </before>
            <after>
                <action method="goodbye"/>
            </after>
        </advice>
    </aspect>

    <translet name="hello">
        <description style="apon">
            |
            |   Runs the helloWorld() method of the sampleAction bean and prints the returned value to the console.
            |   Maybe the words "Hello, World." will be printed on the console.
            |   Is it difficult to find the words "Hello, World." printed on the console?
            |   If so, try running the "hello2" command.
            |---------------------------------------------------------------------------------------------------------
        </description>
        <transform type="transform/text">
            <action id="helloData" bean="sampleAction" method="helloWorld"/>
        </transform>
    </translet>

    <translet name="echo1">
        <description style="apon">
            |It accepts parameters and print them to the console.
        </description>
        <parameters>
            <item name="param1" mandatory="false"/>
            <item name="param2" mandatory="true"/>
        </parameters>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The parameters you entered are:
                |   param1: ${param1}
                |   param2: ${param2}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo2">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="param1" mandatory="true">${prefix} - 1</item>
            <item name="param2">${prefix} - 2</item>
            <item name="param3">${prefix} - 3</item>
        </parameters>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The parameters you entered are:
                |   param1: ${param1}
                |   param2: ${param2}
                |   param3: ${param3}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo3">
        <description style="apon">
            |
            |   It accepts parameters and print them to the console.
            |
        </description>
        <parameters>
            <item name="param1">first ${param1:12345}</item>
            <item name="param2">second ${param2:67890}</item>
            <item name="param3" mandatory="true">third ${param3-1} and ${param3-2}</item>
        </parameters>
        <attributes>
            <item name="attr1">fourth ${param4}</item>
        </attributes>
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |The input parameters and attributes are as follows:
                |   param1: ${param1}
                |   param2: ${param2}
                |   param3: ${param3}
                |   attr1: @{attr1}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="echo ${text}">
        <transform type="transform/text">
            <template engine="token" style="apon">
                |----------------------------------------------------------
                |${text}
                |----------------------------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="login">
        <description style="apon">
            |
            |   If you enter the required ID and password for login, it will be printed on the console.
            |
        </description>
        <request>
            <parameters>
                <item name="email">${emailId}@${emailDomain}</item>
                <item name="password" secret="true"/>
            </parameters>
        </request>
        <transform type="transform/text">
            <template style="apon">
                |-----------------------------------------
                | You entered the following for login:
                |   email: ${email}
                |   password: ${password}
                |-----------------------------------------
            </template>
        </transform>
    </translet>

    <translet name="chpw">
        <description style="apon">
            |
            | If you enter parameters to change the password, it will be printed on the console.
            |
        </description>
        <request>
            <parameters>
                <item name="email">${emailId}@${emailDomain}</item>
                <item name="password" secret="true"/>
                <item name="confirmPassword" secret="true"/>
            </parameters>
        </request>
        <transform type="transform/text">
            <template style="apon">
                |--------------------------------------------------------
                | You entered the following to change your password:
                |   email: ${email}
                |   password: ${password}
                |   confrim password: ${confirmPassword}
                |--------------------------------------------------------
            </template>
        </transform>
    </translet>

    <append resource="config/shell/jline/freemarker-translets.xml"/>

</aspectran>
