=== aspectran/aspectran/aspectran.example/config/aspectran/dtd/aspectran-1.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT aspectran (settings? | apon? | typeAliases* | import* | bean* | translet* | aspect*)*>
<!ATTLIST aspectran
namespace CDATA #IMPLIED
>

<!ELEMENT settings (setting*)>
<!ELEMENT setting (#PCDATA)>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #IMPLIED
>

<!ELEMENT typeAliases (typeAlias*)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT import EMPTY>
<!ATTLIST import
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT item (#PCDATA | value | reference | null)*>
<!ATTLIST item
name CDATA #IMPLIED
value CDATA #IMPLIED
type (item | list | map | set | properties) #IMPLIED
valueType CDATA #IMPLIED
defaultValue CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA | reference | null)*>
<!ATTLIST value
name CDATA #IMPLIED
tokenize (true | false) #IMPLIED
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
bean CDATA #IMPLIED
parameter CDATA #IMPLIED
attribute CDATA #IMPLIED
property CDATA #IMPLIED
>

<!ELEMENT attributes (item*)>

<!ELEMENT properties (item*)>

<!ELEMENT arguments (item*)>

<!ELEMENT parameters (item*)>

<!ELEMENT null EMPTY>

<!ELEMENT apon (#PCDATA)>
<!ATTLIST apon
for (settings | bean) #REQUIRED
>

<!ELEMENT aspect (joinpoint?, settings?, apon?, advice?)>
<!ATTLIST aspect
id ID #IMPLIED
for (translet | scheduler) #IMPLIED
>

<!ELEMENT joinpoint (pointcut*)>
<!ATTLIST joinpoint
scope (translet | request | content | action-content | bean-content | response | action | bean) #IMPLIED
>

<!ELEMENT pointcut (#PCDATA | target)*>
<!ATTLIST pointcut
type (wildcard | regexp | simpleTrigger | cronTrigger) #IMPLIED
>

<!ELEMENT target (#PCDATA | without)*>
<!ATTLIST target
translet CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
>

<!ELEMENT without (#PCDATA)>
<!ATTLIST without
translet CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
>

<!ELEMENT advice ((before?, after?, around?, finally?, exceptionRaized?) | job*)>
<!ATTLIST advice
bean CDATA #IMPLIED
>

<!ELEMENT before (echo | action)>
<!ELEMENT after (echo | action)>
<!ELEMENT around (echo | action)>
<!ELEMENT finally (echo | action)>
<!ELEMENT exceptionRaized (action?, responseByContentType*, defaultResponse?)>

<!ELEMENT job EMPTY>
<!ATTLIST job
translet CDATA #REQUIRED
disabled (true | false) #IMPLIED
>

<!ELEMENT bean (features?, constructor?, properties*)>
<!ATTLIST bean
id CDATA #IMPLIED
class CDATA #IMPLIED
scope (singleton | prototype | request | session | application) #IMPLIED
factoryMethod CDATA #IMPLIED
initMethod CDATA #IMPLIED
destoryMethod CDATA #IMPLIED
lazyInit (true | false) #IMPLIED
parent CDATA #IMPLIED
override (true | false) #IMPLIED
>

<!ELEMENT features (class?, scope?, factoryMethod?, initMethod?, destroyMethod?, lazyInit?, poolSize?)>

<!ELEMENT class (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT factoryMethod (#PCDATA)>
<!ELEMENT initMethod (#PCDATA)>
<!ELEMENT destroyMethod (#PCDATA)>
<!ELEMENT lazyInit (#PCDATA)>
<!ELEMENT poolSize (#PCDATA)>

<!ELEMENT constructor (arguments?)>

<!ELEMENT translet ((request?, (echo? | action? | include?)*, (transform | dispatch | redirect | forward)?) | (request?, contents?, response*, exception?))>
<!ATTLIST translet
name CDATA #REQUIRED
hidden (true | false) #IMPLIED
extends CDATA #IMPLIED
>

<!ELEMENT request (attributes?, multiparts?)>
<!ATTLIST request
method CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>

<!ELEMENT multiparts (fileItem*)>

<!ELEMENT fileItem EMPTY>
<!ATTLIST fileItem
name CDATA #REQUIRED
>

<!ELEMENT contents (content*)>

<!ELEMENT content (echo? | action? | include?)*>
<!ATTLIST content
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT echo (#PCDATA | item | value | null)*>
<!ATTLIST echo
id CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT action (arguments?, properties?)>
<!ATTLIST action
id CDATA #IMPLIED
bean CDATA #IMPLIED
method CDATA #IMPLIED
hidden (true | false) #IMPLIED
>

<!ELEMENT include (attributes?)>
<!ATTLIST include
id CDATA #IMPLIED
translet CDATA #REQUIRED
hidden (true | false) #IMPLIED
>

<!ELEMENT response (transform? | dispatch? | redirect? | forward?)>
<!ATTLIST response
name CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>
<!ELEMENT exception (responseByContentType*, defaultResponse?)>

<!ELEMENT responseByContentType (transform? | dispatch? | redirect? | forward?)*>
<!ATTLIST responseByContentType
exceptionType CDATA #IMPLIED
>
<!ELEMENT defaultResponse (transform? | dispatch? | redirect? | forward?)>

<!ELEMENT transform ((echo? | action? | include?)*, template?)>
<!ATTLIST transform
type CDATA #IMPLIED
contentType CDATA #IMPLIED
characterEncoding CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template
resource CDATA #IMPLIED
file CDATA #IMPLIED
url CDATA #IMPLIED
encoding CDATA #IMPLIED
noCache (true | false) #IMPLIED
>

<!ELEMENT dispatch ((echo? | action? | include?)*, template)>
<!ATTLIST dispatch
contentType CDATA #IMPLIED
>

<!ELEMENT redirect ((echo? | action? | include?)*, url?, parameters?)>
<!ATTLIST redirect
contentType CDATA #IMPLIED
url CDATA #IMPLIED
translet CDATA #IMPLIED
excludeNullParameters CDATA #IMPLIED
>
<!ELEMENT url (#PCDATA)>

<!ELEMENT forward ((echo? | action? | include?)*, url?, parameters?)>
<!ATTLIST forward
contentType CDATA #IMPLIED
translet CDATA #IMPLIED
>

=== aspectran/aspectran/aspectran.example/webapp/WEB-INF/aspectran/config/example-root.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE aspectran PUBLIC "-//aspectran.com//DTD Aspectran 1.0//EN"
                           "../dtd/aspectran-1.0.dtd">

<aspectran>

	<settings>
		<setting name="transletNamePattern" value="/example/*"/>
		<setting name="transletInterfaceClass" value="com.aspectran.web.activity.WebTranslet"/>
		<setting name="transletImplementClass" value="com.aspectran.web.activity.WebTransletImpl"/>
		<setting name="activityDefaultHandler" value="webActivityDefaultHandler"/>
		<setting name="useNamespaces" value="true"/>
		<setting name="nullableContentId" value="true"/>
		<setting name="nullableActionId" value="true"/>
	</settings>
	
	<import file="/WEB-INF/aspectran/config/example-scheduler.xml"/>
	
	<bean id="webActivityDefaultHandler" class="com.aspectran.web.activity.WebActivityDefaultHandler" scope="singleton"/>
	<bean id="jspViewDispatcher" class="com.aspectran.web.view.JspViewDispatcher" scope="singleton"/>
	<bean id="example.*" class="com.aspectran.example.**.*Action" scope="singleton"/>
	<bean id="advice.*" class="com.aspectran.example.aspect.**.*Advice" scope="session"/>
	<bean id="sampleBean" class="com.aspectran.example.bean.SampleBean" scope="singleton"/>
	
	<aspect id="defaultRequestRule">
		<joinpoint scope="request"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="multipart.maxRequestSize" value="10M"/>
			<setting name="multipart.temporaryFilePath" value="/d:/"/>
		</settings>
	</aspect>
	
	<aspect id="defaultResponseRule">
		<joinpoint scope="response"/>
		<settings>
			<setting name="characterEncoding" value="utf-8"/>
			<setting name="defaultContentType" value="text/html"/>
			<setting name="viewDispatcher" value="jspViewDispatcher"/>
		</settings>
	</aspect>
	
	<aspect id="defaultResponseRule2">
		<joinpoint scope="response"/>
		<settings>
			characterEncoding: utf-8
			multipart.maxRequestSize: 10M
			multipart.temporaryFilePath: /d:/
		</settings>
	</aspect>

	<aspect id="exception1">
		<joinpoint scope="translet">
			<pointcut>
				<target translet="/example/hello/*"/>
			</pointcut>
		</joinpoint>
		<advice>
			<exceptionRaized>
				<responseByContentType exceptionType="java.lang.reflect.InvocationTargetException">
					<transform contentType="text/xml" type="transform/xml">
						<echo>
							errorCode: E0001
							message: error occured.
						</echo>
						<echo>
							<item type="map">
								<value name="errorCode">E0001</value>
								<value name="message">error occured.</value>
							</item>
						</echo>
					</transform>
				</responseByContentType>
			</exceptionRaized>
		</advice>
	</aspect>

	<aspect id="helloAdvice">
		<joinpoint scope="content">
			<pointcut>
				<target>
					+: /example/hello/*@example.hello.HelloAction^applyTheAdvice
				</target>
				<target translet="/example/hello/*" bean="example.hello.HelloAction" method="applyTheAdvice">
					<exclude translet="/example/hello/*" bean="example.hello.HelloAction" method="applyTheAdvice"/>
				</target>
			</pointcut>
		</joinpoint>
		<advice bean="advice.HelloAdvice">
			<before>
				<action method="beforeCountTo10"/>
			</before>
			<after>
				<action method="afterCountTo10"/>
			</after>
		</advice>
	</aspect>

	<translet name="/hello">
		<transform type="transform/text">
			<template>
				hello~ ${name}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10">
		<transform type="transform/text">
			<action id="result1" bean="example.hello.HelloAction" method="countTo10"/>
			<template>
@{result1}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10twice">
		<action id="result1" bean="example.hello.HelloAction" method="countTo10"/>
		<action id="result2" bean="example.hello.HelloAction" method="countTo10"/>
		<transform type="transform/text">
			<template>
(first)
@{result1}
(second)
@{result2}
			</template>
		</transform>
	</translet>

	<translet name="hello/countTo10.xml">
		<transform type="transform/xml">
			<action id="result" bean="example.hello.HelloAction" method="countTo10AsArray"/>
		</transform>
	</translet>

	<translet name="hello/countTo10ext">
		<response>
			<transform type="transform/text">
				<action id="result" bean="example.hello.HelloAction" method="countTo10"/>
				<template>
					@{result}
				</template>
			</transform>
		</response>
		<response name=".xml">
			<transform type="transform/xml">
				<action bean="example.hello.HelloAction" method="countTo10AsArray"/>
			</transform>
		</response>
	</translet>

	<translet name="hello/applyTheAdvice.xml">
		<transform type="transform/xml">
			<action id="applyTheAdvice" bean="example.hello.HelloAction" method="applyTheAdvice"/>
		</transform>
	</translet>

	<translet name="echo">
		<transform type="transform/text" contentType="text/html">
			<echo id="echo">
				<item name="map0" type="map" valueType="string" tokenize="true">
					<value name="item1">${item1:default1}</value>
					<value name="item2">${item2:default2}</value>
				</item>
			</echo>
			<template>
<![CDATA[
<html>
<style>
body { background-color: blue; color: white; }
dt { font-weight: bold; color: yellow; }
</style>
<body>
	<dl>
		<dt>item1</dt>
		<dd>@{echo^map0.item1}</dd>
		<dt>item2</dt>
		<dd>@{echo^map0.item2}</dd>
	</dl>
</body>
</html>
]]>
			</template>
		</transform>
	</translet>

	<translet name="hello/sampleBean.txt">
		<transform type="transform/text">
			<action id="sample" bean="sampleBean" method="hello"/>
			<template>
text: @{sample}
The length of the output string is @{sample^length:0} bytes.
			</template>
		</transform>
	</translet>

	<translet name="goNaver">
		<redirect url="http://www.naver.com"/>
	</translet>
	
</aspectran>
